apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ky1x5zd6m-nodejs 
  janus-idp.io/tekton: ky1x5zd6m-nodejs
  backstage.io/kubernetes-id: ky1x5zd6m-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ky1x5zd6m-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  